//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.user_db = new HashSet<user_db>();
            this.thanhtoans = new HashSet<thanhtoan>();
        }
    
        public int idcustomer { get; set; }
        public string customer_name { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
        public string customer_email { get; set; }
    
        public virtual ICollection<user_db> user_db { get; set; }
        public virtual ICollection<thanhtoan> thanhtoans { get; set; }
    }
}
