//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banhangEntities : DbContext
    {
        public banhangEntities()
            : base("name=banhangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customer> customers { get; set; }
        public DbSet<phone> phones { get; set; }
        public DbSet<role_db> role_db { get; set; }
        public DbSet<thanhtoan> thanhtoans { get; set; }
        public DbSet<user_db> user_db { get; set; }

    }
}
