//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_db
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public int role_id { get; set; }
        public Nullable<int> customerId { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual role_db role_db { get; set; }
    }
}
